finchcollector/finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

finchcollector/main_app/urls.py
# setup home path
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    
    path('about/', views.about, name='about'),
    
    path('all_finches/', views.finches_index, name='index'),
    
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    
    path('finches/<int:finch_id>/add_sighting/', views.add_sighting, name='add_sighting'),
]

finchcollector/main_app/models.py
from django.db import models
from django.urls import reverse


WHEN = (
    ('Da', 'Dawn'),
    ('LM', 'Late Morning'),
    ('M', 'Midday'),
    ('EE', 'Early Evening'),
    ('ME', 'Mid Evening'),
    ('Du', 'Dusk'),
)

# Create your models here.
class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    Latin = models.TextField(max_length=250)
    age = models.IntegerField()
    
    # once model is created here run python3 manage.py makemigrations to create model in psql database
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"finch_id": self.id})
    
    

class Sighting(models.Model):
    date = models.DateField('Finch Sighting')
    time = models.CharField(max_length=2, choices=WHEN, default=WHEN[0][0]
    
    )
    
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)
   
    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_time_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']
    
 

finchcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Sighting

class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = ['date','time'] 

finchcollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch
from .forms import SightingForm

# finches = [
#     { 'name': 'Tweety', 'breed': 'House', 'Latin': 'Haemorhous Mexicanus', 'age': 3 },
#     { 'name': 'Sachmo', 'breed': 'Purple', 'Latin': 'Haemorhous Purpureus', 'age': 2 }, 
#     { 'name': 'River', 'breed': 'American Gold',
#      'Latin': 'Spinus Tristis', 'age': 0 },
# ]

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html',{
        'finches': finches
    })
    
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    sighting_form = SightingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch,
        'sighting_form': sighting_form,
    })
    
def add_sighting(request, finch_id):
    # create a ModelForm instance using the data in request.POST
    form = SightingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the cat_id assigned
        new_sighting = form.save(commit=False)
        new_sighting.finch_id = finch_id
        new_sighting.save()
    return redirect('detail', finch_id=finch_id)
    
class FinchCreate(CreateView):
    model = Finch
    fields = '__all__'
    # Special string pattern Django will use
    # success_url = '/finches/{finch_id}' <- what it may look like under the hood
    # Or if you wanted to redirect to the index page
    # success_url = '/finches' 
    
class FinchUpdate(UpdateView):
    model = Finch
    fields = ['breed', 'Latin', 'age']
    

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/all_finches'
    

    

finchcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content%}
        <div class='about'>
        <h1>The Finch Collector</h1>
        <hr>
        <p >Enjoy the collection of Finches brought to you by Anthony Blalock</p>
        </div>

{% endblock%}

finchcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="center">All Rights Reserved, &copy; 2023 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

finchcollector/main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content%}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Latin: {{ finch.Latin }}</p>
        {% if finch.age > 0 %}
          <p>Age: {{ finch.age }}</p>
        {% else %}
          <p>Age: Chick</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id%}">Edit</a>
        <a href="{% url 'finches_delete' finch.id%}">Delete</a>
      </div>  
    </div>
  </div>
  <div class="col s6">
    {% comment %} beginning of form to add finch sighting {% endcomment %}
    <form action="{% url 'add_sighting' finch.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ sighting_form.as_p }}
      <input type="submit" class="btn" value="Add Sighting">
    </form>
    {% comment %} end of form to add finch sighting {% endcomment %}

    {% comment %} display of record of finch sighting below {% endcomment %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>When</th></tr>
      </thead>
      <tbody>
        {% for sighting in finch.sighting_set.all %}
          <tr>
            <td>{{sighting.date}}</td>
            <td>{{sighting.get_time_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

   // add additional JS to initialize select below
   const selectEl = document.getElementById('id_time');
   M.FormSelect.init(selectEl);
</script>
{% endblock%}

finchcollector/main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1 id='about-title'>Finch List</h1>

{% for finch in finches %}
  <div class="card">
    <a href="{% url 'detail' finch.id %}">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
    </a>
    </div>
  </div>
{% endfor %}

{% endblock %}

{% comment %} info cut form original post {% endcomment %}
{% comment %} <p>Breed: {{ finch.breed }}</p>
      <p>Latin Name: {{ finch.Latin }}</p>
      {% if finch.age > 0 %}
        <p>Age: {{ finch.age }}</p>
      {% else %}
        <p>Age: Chick</p>
      {% endif %} {% endcomment %}s

finchcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content%}

<h1>Finch Collector Lab</h1>
        
{% endblock%}
   

finchcollector/main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content%}

    <h1>Delete Finch</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">

        <a href="{% url 'detail' finch.id %}">Cancel</a>
    </form>

{% endblock %}

finchcollector/main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content%}
    {% if object%}
    <h1>Edit: <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Finch</h1>
    {% endif %}
    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="POST">
        <!-- Django requires the following for security purposes -->
        {% csrf_token%}
        <table>
            <!-- Render the inputs inside of <tr>s & <td>s -->
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>

{% endblock %}